import { StyleInfo, MusicStyle } from "./types";

export const MUSIC_STYLES: StyleInfo[] = [
  {
    id: "rock",
    name: "Rock",
    emoji: "🎸",
    description: "Técnicas de rock clássico, hard rock e rock alternativo",
    difficulty: "Intermediário",
    lessonCount: 12,
  },
  {
    id: "jazz",
    name: "Jazz",
    emoji: "🎷",
    description: "Improviso, walking bass e harmonia jazzística",
    difficulty: "Avançado",
    lessonCount: 15,
  },
  {
    id: "funk",
    name: "Funk",
    emoji: "🎵",
    description: "Grooves, slap bass e técnicas percussivas",
    difficulty: "Intermediário",
    lessonCount: 14,
  },
  {
    id: "samba",
    name: "Samba",
    emoji: "🥁",
    description: "Ritmos brasileiros, samba no pé e variações",
    difficulty: "Intermediário",
    lessonCount: 10,
  },
  {
    id: "blues",
    name: "Blues",
    emoji: "🎼",
    description: "Blues clássico, pentatônica e feel bluesy",
    difficulty: "Iniciante",
    lessonCount: 8,
  },
  {
    id: "pop",
    name: "Pop",
    emoji: "⭐",
    description: "Linhas de baixo pop, harmonia e produção",
    difficulty: "Iniciante",
    lessonCount: 11,
  },
  {
    id: "metal",
    name: "Metal",
    emoji: "🤘",
    description: "Técnicas de metal, distorção e velocidade",
    difficulty: "Avançado",
    lessonCount: 9,
  },
  {
    id: "reggae",
    name: "Reggae",
    emoji: "🌴",
    description: "Riddim, one-drop e estilo reggae",
    difficulty: "Iniciante",
    lessonCount: 7,
  },
  {
    id: "gospel",
    name: "Gospel",
    emoji: "🙏",
    description: "Harmonia gospel, grooves e expressão",
    difficulty: "Intermediário",
    lessonCount: 6,
  },
  {
    id: "bossa-nova",
    name: "Bossa Nova",
    emoji: "🎹",
    description: "Ritmo bossa nova, harmonia sofisticada",
    difficulty: "Avançado",
    lessonCount: 8,
  },
  {
    id: "forro",
    name: "Forró",
    emoji: "🎪",
    description: "Ritmos nordestinos, baião e xote",
    difficulty: "Intermediário",
    lessonCount: 5,
  },
  {
    id: "axe",
    name: "Axé",
    emoji: "🎊",
    description: "Ritmos afro-brasileiros, energia e groove",
    difficulty: "Intermediário",
    lessonCount: 6,
  },
  {
    id: "pagode",
    name: "Pagode",
    emoji: "🎺",
    description: "Samba pagode, cavaquinho e bateria",
    difficulty: "Intermediário",
    lessonCount: 7,
  },
  {
    id: "mpb",
    name: "MPB",
    emoji: "🎤",
    description: "Música Popular Brasileira, harmonia complexa",
    difficulty: "Avançado",
    lessonCount: 10,
  },
  {
    id: "eletronico",
    name: "Eletrônico",
    emoji: "🎚️",
    description: "Eletrônico, sintetizadores e produção digital",
    difficulty: "Intermediário",
    lessonCount: 8,
  },
];

export const MOCK_USER = {
  id: "u1",
  name: "Você",
  email: "aluno@bassclass.com",
  avatar: "https://i.pravatar.cc/150?img=3",
  lessonsCompleted: 0,
  hoursStudied: 0,
  stylesLearned: 0,
};

export const PROFESSOR_DANIEL = {
  name: "Prof. Daniel Gondim",
  title: "Contrabaixista Profissional",
  avatar: "https://i.pravatar.cc/150?img=12",
  bio: "Contrabaixista profissional com mais de 20 anos de experiência em diversos estilos musicais.",
  pricePerHour: 150,
};

// Available time slots for lessons (next 2 weeks)
export const AVAILABLE_SLOTS = [
  { id: "s1", date: "2026-05-06", time: "09:00", available: true },
  { id: "s2", date: "2026-05-06", time: "11:00", available: true },
  { id: "s3", date: "2026-05-06", time: "14:00", available: true },
  { id: "s4", date: "2026-05-06", time: "16:00", available: true },
  { id: "s5", date: "2026-05-07", time: "09:00", available: true },
  { id: "s6", date: "2026-05-07", time: "14:00", available: true },
  { id: "s7", date: "2026-05-08", time: "10:00", available: true },
  { id: "s8", date: "2026-05-08", time: "15:00", available: true },
  { id: "s9", date: "2026-05-09", time: "09:00", available: true },
  { id: "s10", date: "2026-05-09", time: "16:00", available: true },
  { id: "s11", date: "2026-05-12", time: "11:00", available: true },
  { id: "s12", date: "2026-05-12", time: "14:00", available: true },
];
