/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/video-call`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lessons` | `/lessons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mentors` | `/mentors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownInputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/lesson/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/mentor/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/schedule/[mentorId]`, params: Router.UnknownInputParams & { mentorId: string | number; } } | { pathname: `/schedule/[styleId]`, params: Router.UnknownInputParams & { styleId: string | number; } } | { pathname: `/session/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/style/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/video-call`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lessons` | `/lessons`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mentors` | `/mentors`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sessions` | `/sessions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownOutputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownOutputParams; } | { pathname: `/lesson/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/mentor/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/schedule/[mentorId]`, params: Router.UnknownOutputParams & { mentorId: string; } } | { pathname: `/schedule/[styleId]`, params: Router.UnknownOutputParams & { styleId: string; } } | { pathname: `/session/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/style/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/video-call${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lessons${`?${string}` | `#${string}` | ''}` | `/lessons${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mentors${`?${string}` | `#${string}` | ''}` | `/mentors${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sessions${`?${string}` | `#${string}` | ''}` | `/sessions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `/dev/theme-lab${`?${string}` | `#${string}` | ''}` | `/oauth/callback${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/video-call`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lessons` | `/lessons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mentors` | `/mentors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownInputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownInputParams; } | `/lesson/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/mentor/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/schedule/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/schedule/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/session/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/style/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/lesson/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/mentor/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/schedule/[mentorId]`, params: Router.UnknownInputParams & { mentorId: string | number; } } | { pathname: `/schedule/[styleId]`, params: Router.UnknownInputParams & { styleId: string | number; } } | { pathname: `/session/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/style/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
